/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_b_facedetection_MainActivity */

#ifndef _Included_com_example_b_facedetection_MainActivity
#define _Included_com_example_b_facedetection_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_b_facedetection_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_b_facedetection_MainActivity_setting(JNIEnv *, jobject);
JNIEXPORT jbyteArray JNICALL Java_com_example_b_facedetection_Preview_colorGrayArray(JNIEnv *, jobject , jbyteArray ba);
JNIEXPORT void JNICALL Java_com_example_b_facedetection_Preview_findFace(JNIEnv* env, jobject thiz, jbyteArray source,jint width, jint height, jobject cp);
#ifdef __cplusplus
}
#endif
#endif
